### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [lang1427/vue-typescript-music#3]
您好，我们对您分享的这个“网易云WebApp项目”十分感兴趣，想要与您进行商务合作，但github上没没有留下您的联系方式，可以在此留下您的邮箱或微信联系方式，方便我们与您建立联系吗？

**Comment by lang1427** [comment]
感谢您的认可，but  此项目不提供商务合作，也禁止将此项目商用，商用所造成的一切后果，本人概不承担  and  wx：lang18770971427
